### ISSUE TITLE
Should have a session on ScienceOps 

### ISSUE THREAD

**Issue by sharatsc** [PAPIsdotio/global-2018#1]
ScienceOps is devops for data science. One of the challenges of industrial machine learning/AI is operationalization. We should invite industry participants to describe their war stories in this session.

**Comment by louisdorard** [comment]
Good point. I'll bring this up in the next call with our Program Chair. We should get you involved in the Program Committee @sharatsc! I'll email you about that :)

**Comment by louisdorard** [comment]
Added a track named "ML Engineering & ScienceOps". @sharatsc would you be interested in chairing that track? We would really appreciate your help to invite people to submit proposals to this track!

**Comment by sharatsc** [comment]
I'd be more than happy to.
